name: ronaldinhothc@gmail.com
description:  W przypadku chęci zgłoszenia błędu / propozycji anonimowo lub bez rejestracji na GitHubie, skontaktuj się za pomocą maila **ronaldinhothc@gmail.com**
body:
- type: markdown
  attributes:
    value: "Czysto informacyjne, do not submit please :)"
- type: checkboxes
  id: cat-preferences
  attributes:
    label: "Czysto informacyjne, do not submit please :)"
    description: "Czysto informacyjne, do not submit please :)"
    options:
      - label: Nie chcę tworzyć tego zgłoszenia - zostałem zmuszony
        required: true
