name: Nowy punkt, znam jego lokalizacje
description: Zaproponuj nowy punkt na mapie znając jego lokalizacje
labels: ["nowy punkt"]
body:
  - type: markdown
    attributes:
      value: |
        W przypadku chęci zgłoszenia błędu / propozycji anonimowo lub bez rejestracji na GitHubie, skontaktuj się za pomocą
        -> maila: ronaldinhothc@gmail.com
  - type: markdown
    attributes:
      value: |
        Zgłaszając zmiany zgadzasz się na [regulamin dostępny tutaj](https://github.com/polskie-mapy/data/issues/426) ;P
  - type: input
    id: name
    attributes:
      label: Nazwa punktu
      description: "Proponowana nazwa punktu / nazwa filmiku"
    validations:
      required: true
  - type: input
    id: coords
    attributes:
      label: Lokalizacja zdarzenia
      value: brak danych
    validations:
      required: true
  - type: dropdown
    id: coordsType
    attributes:
      label: Dokładność lokalizacji
      options:
        - Dokładna lokalizacja
        - Niedokładna/przybliżona lokalizacja
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: "Linki do zdarzenia / filmu"
      description: Może być więcej niż jedno źródło
    validations:
     required: true
  - type: input
    id: icon
    attributes:
      label: Proponowana ikona
      description: "Jeśli chcesz możesz zaproponować ikonę z tej listy -> https://fontawesome.com/search?o=r&s=solid%2Cregular&f=classic"
    validations:
     required: false
  - type: input
    id: color
    attributes:
      label: Proponowany kolor
      description: "Jeśli chcesz możesz zaproponować kolor punktu, najlepiej w formacie #rrggbb -> https://www.google.com/search?q=color+picker skopiuj wartość z pola **HEX**"
    validations:
     required: false
  - type: textarea
    id: reasons
    attributes:
      label: Dlaczego ten punkt powinien znaleźć się na mapie?
    validations:
     required: true
